%YAML:1.0
#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
pose_body_to_left_camera: !!opencv-matrix # this statement is necessary.
  rows: 4
  cols: 4
  dt: f
  data: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]

pose_body_to_right_camera: !!opencv-matrix # this statement is necessary.
  rows: 4
  cols: 4
  dt: f
  data: [1.0, 0.0, 0.0, 0.05, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
