%YAML:1.0
#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
# Camera calibration and distortion parameters (OpenCV) 
left_camera.doUndistortion: 0 # 0: do not undistort an image, 1: undistort an image
left_camera.fx: 419.617919921875
left_camera.fy: 419.617919921875
left_camera.cx: 424.94940185546875
left_camera.cy: 237.3017578125

left_camera.k1: 0.0
left_camera.k2: 0.0
left_camera.k3: 0.0
left_camera.p1: 0.0
left_camera.p2: 0.0

left_camera.width: 848
left_camera.height: 480

right_camera.doUndistortion: 0 # 0: do not undistort an image, 1: undistort an image
right_camera.fx: 419.617919921875
right_camera.fy: 419.617919921875
right_camera.cx: 424.94940185546875
right_camera.cy: 237.3017578125

right_camera.k1: 0.0
right_camera.k2: 0.0
right_camera.k3: 0.0
right_camera.p1: 0.0
right_camera.p2: 0.0

right_camera.width: 848
right_camera.height: 480