---
#--------------------------------------------------------------------------------------------
# User setting Parameters
#--------------------------------------------------------------------------------------------
# Parameters of feature tracker
feature_extractor:
  af: 1
