%YAML:1.0
#--------------------------------------------------------------------------------------------
# User setting Parameters
#--------------------------------------------------------------------------------------------

# Parameters of feature tracker
feature_tracker.thres_error: 40.0
feature_tracker.thres_bidirection: 0.5
feature_tracker.thres_sampson: 0.5
feature_tracker.window_size: 15
feature_tracker.max_level: 6

# Parameters of map update
map_update.thres_parallax: 1.0

# Parameters of feature extractor
feature_extractor.n_features: 4000
feature_extractor.n_bins_u: 32
feature_extractor.n_bins_v: 20
feature_extractor.thres_fastscore: 15.0
feature_extractor.radius: 5.0

# Parameters of motion estimator
motion_estimator.thres_1p_error: 120.0 # pixels
motion_estimator.thres_5p_error: 1.0 # pixels
motion_estimator.thres_poseba_error: 3.0 # pixels

motion_estimator.lba.max_iter: 6

# Parameters of keyframe update
keyframe_update.thres_alive_ratio: 0.7
keyframe_update.thres_mean_parallax: 1.0
keyframe_update.thres_trans: 1.0 # meters
keyframe_update.thres_rotation: 4.0 # degrees
